# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- branch1

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: building
        steps:
        
        - task: TerraformTaskV4@4
          displayName: tf-init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/mo-ap/tf-infra'
            backendAzureRmUseEnvironmentVariablesForAuthentication: false
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'tf-service-connection'
            backendAzureRmResourceGroupName: 'backend-rg'
            backendAzureRmStorageAccountName: 'tfbackendgglearn'
            backendAzureRmContainerName: 'tf-backend'
            backendAzureRmKey: 'backend.tfstate'

        - task: TerraformTaskV4@4
          displayName: tf-plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/mo-ap/tf-infra'
            environmentServiceNameAzureRM: 'tf-service-connection'
          
        - task: ArchiveFiles@2
          displayName: archive-files
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/mo-ap/tf-infra'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: create-artifact
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: '$(Build.BuildId)-build'
            publishLocation: 'Container'
          
        - task: UniversalPackages@0
          displayName: publish-to-feed
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.ArtifactStagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: '1576bf74-cb00-4adc-bf92-da9e9fc15547/13f08513-58ee-443c-92b5-aa2ad9bb4a07'
            vstsFeedPackagePublish: 'mo-ap-package'
            versionOption: 'minor'

        